baseurl:     /
server:      true
auto:        true
lsi:         false
server_port: 4000
pygments:    true
markdown:    rdiscount
permalink:   /:title

title:            DolphinBoy
url:              http://dolphinboy.me
feed:             /atom.xml
author:
    name:         DolphinBoy
    email:        dolphinboyo@gmail.com
    twitter:      twitter.com/3kqing
    weibo:        weibo.com/longxinanlan
description:      "DolphinBoy,Blog,Jekyll"
author_info:      <a href="http://dolphinboy.me/about">DolphinBoy</a>

copyright:
    - Design by <a href="http://dolphinboy.me/about" title="DolphinBoy" target="_blank">DolphinBoy</a>. &copy; 2013

javascript:
    - /js/jquery-1.9.0.min.js
    - /js/jquery-1.9.0.min.js